### ISSUE TITLE
lab2 elective 2

### ISSUE THREAD

**Issue by wehob** [GrassLab/osc2021#57]
elective 2 requires us to parse dtb and implement an interface that takes a callback function argument.

So what should I do is to implement a parse function that accepts the driver function as input (what driver may be the input to this function, uart_init() is a driver function but I don't think that is a valid one), and match itself by checking the node’s name and properties(what should I do when it matches? return true?)

Thank you for your reply

**Comment by t0037799** [comment]
```py
import dtb
def uart_probe(device_node):
  if 'uart' not in device_node.compatible:
    return
  uart_init(device_node, ...)

def rtx3080ti_probe(device_node):
  if 'rtx3080ti' not in device_node.compatible:
    return
  rtx3080ti_init(device_node, ...)

driver_probe_funcs = [uart_probe,  rtx3080ti_probe, ...] 
dtb.init()
for f in driver_probe_funcs:
  dtb.foreach_node(f)
```

The above pseudocode is a possible implementation and how to use it.
The device tree module provides a function to walk all device nodes in dtb and call the provided callback functions with the device node.
In the example, because uart is in rpi3's dtb, so it'll be matched when walking the device tree.
After the device node and the driver matches, the driver can use the device node's property for initialization.
On the other hand,  rtx3080ti is not in rpi3's dtb so, it's callback function never find matched device node and never get initialized.

You can either parse dtb ahead of time to construct a device tree, or on the fly when someone calls `dtb.foreach_node()`.

**Finally, if you have any problem with the documentation, please submit issue at [documentation's repository](https://github.com/GrassLab/NYCU_Operating_System_Capstone)**
